/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module cnt (
  input rst,
  input clk,
  input incr,
  output [2:0] out
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign s6 = ~ rst;
  assign s0 = ((s1 ^ incr) & s6);
  assign s2 = ((s3 ^ (s1 & incr)) & s6);
  assign s4 = ((s5 ^ (s3 & s1 & incr)) & s6);
  // b0
  d_ff d_ff_i0 (
    .d( s0 ),
    .clk( clk ),
    .q( s1 )
  );
  // b1
  d_ff d_ff_i1 (
    .d( s2 ),
    .clk( clk ),
    .q( s3 )
  );
  // b2
  d_ff d_ff_i2 (
    .d( s4 ),
    .clk( clk ),
    .q( s5 )
  );
  assign out[0] = s1;
  assign out[1] = s3;
  assign out[2] = s5;
endmodule
