/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module d_ff (
  input d,
  input clk,
  output q,
  output nq
);
  wire s0;
  wire s1;
  wire s2;
  assign s0 = ~ clk;
  // master
  d_latch d_latch_i0 (
    .d( d ),
    .e( s0 ),
    .q( s1 )
  );
  assign s2 = ~ s0;
  // slave
  d_latch d_latch_i1 (
    .d( s1 ),
    .e( s2 ),
    .q( q ),
    .nq( nq )
  );
endmodule
