/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module d_latch (
  input d,
  input e,
  output q,
  output nq
);
  wire nq_temp;
  wire q_temp;
  assign q_temp = ~ ((~ d & e) | nq_temp);
  assign nq_temp = ~ (q_temp | (e & d));
  assign q = q_temp;
  assign nq = nq_temp;
endmodule
