/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module fac (
  input y,
  input x,
  input c_in,
  output z,
  output c_out
);
  assign z = (y ^ x ^ c_in);
  assign c_out = ((y & x) | (y & c_in) | (x & c_in));
endmodule
