// generated by Digital
module reg_1 (
  input in,
  input load,
  input clk,
  input rst,
  output out
);
  wire s0;
  wire out_temp;
  assign s0 = (((out_temp & ~ load) | (in & load)) & ~ rst);
  d_ff d_ff_i0 (
    .d( s0 ),
    .clk( clk ),
    .q( out_temp )
  );
  assign out = out_temp;
endmodule
