
//Generated by Digital

module shift_reg (
  input clk,
  input rst,
  input [7:0] in,
  input b7,
  input b0,
  input [1:0] sel,
  input load,
  output [7:0] out
);
  wire s0;
  wire s1;
  wire [7:0] s2;
  wire s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17;
  wire [7:0] s18;
  wire [7:0] s19;
  wire [7:0] s20;
  assign s0 = ~ rst;
  assign s1 = (s2[0] & s0);
  assign s16 = (s2[1] & s0);
  assign s11 = (s2[2] & s0);
  assign s13 = (s2[3] & s0);
  assign s7 = (s2[4] & s0);
  assign s9 = (s2[5] & s0);
  assign s3 = (s2[6] & s0);
  assign s5 = (s2[7] & s0);
  assign s19[0] = s17;
  assign s19[1] = s12;
  assign s19[2] = s14;
  assign s19[3] = s8;
  assign s19[4] = s10;
  assign s19[5] = s4;
  assign s19[6] = s6;
  assign s19[7] = b7;
  assign s20[0] = b0;
  assign s20[1] = s15;
  assign s20[2] = s17;
  assign s20[3] = s12;
  assign s20[4] = s14;
  assign s20[5] = s8;
  assign s20[6] = s10;
  assign s20[7] = s4;
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i0 (
    .sel( sel ),
    .in_0( s18 ),
    .in_1( s19 ),
    .in_2( s20 ),
    .in_3( s18 ),
    .out( out )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i1 (
    .sel( load ),
    .in_0( s18 ),
    .in_1( in ),
    .out( s2 )
  );
  d_ff d_ff_i2 (
    .d( s3 ),
    .clk( clk ),
    .q( s4 )
  );
  d_ff d_ff_i3 (
    .d( s5 ),
    .clk( clk ),
    .q( s6 )
  );
  d_ff d_ff_i4 (
    .d( s7 ),
    .clk( clk ),
    .q( s8 )
  );
  d_ff d_ff_i5 (
    .d( s9 ),
    .clk( clk ),
    .q( s10 )
  );
  d_ff d_ff_i6 (
    .d( s11 ),
    .clk( clk ),
    .q( s12 )
  );
  d_ff d_ff_i7 (
    .d( s13 ),
    .clk( clk ),
    .q( s14 )
  );
  d_ff d_ff_i8 (
    .d( s1 ),
    .clk( clk ),
    .q( s15 )
  );
  d_ff d_ff_i9 (
    .d( s16 ),
    .clk( clk ),
    .q( s17 )
  );
  assign s18[0] = s15;
  assign s18[1] = s17;
  assign s18[2] = s12;
  assign s18[3] = s14;
  assign s18[4] = s8;
  assign s18[5] = s10;
  assign s18[6] = s4;
  assign s18[7] = s6;
endmodule
